### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shiraji** [shiraji/intellij-plugin-with-gradle-wizard#1]
TODO
- [x] add settings
- [x] add src/main/java source directory
- [x] add build.gradle
- [x] add src/main/resources/META-INF/plugin.xml
- [x] add .idea/runConfigurations/runIdea.xml
- [x] add .idea/runConfigurations/buildPlugin.xml
- [x] scratch GradleFrameworksWizardStep2 since this is copy & paste of framework suppot. not language support
- [x] if kotlin framework is selected, add kotlin lib info
- [x] add property setting that save previous vendor info/gradle-intellij-plugin/intellij version
- [x] clean up package
- [x] refactor file name
- [x] refactor constant
- [x] write as kotlin

---
- [ ] add options (if I find time. if not, then release it and put this feature later version.)

---
- [x] add this plugin's README
- [x] add screenshots
- [x] add this plugin's travis scripts

---

Created by gradle not this plugin.
- [x] add gradlew
- [x] add gradlew.bat
- [x] add gradle/*

---

http://www.jetbrains.org/intellij/sdk/docs/reference_guide/project_wizard.html

https://github.com/JetBrains/intellij-community/blob/9d6477485d37e796036ee524788231f2f47e6ada/plugins/gradle/src/org/jetbrains/plugins/gradle/service/project/wizard/GradleModuleBuilder.java

https://github.com/JetBrains/intellij-community/blob/10a4c91dbfca935b4b5531003fd8c13b56e66202/plugins/gradle/src/org/jetbrains/plugins/gradle/service/project/wizard/GradleModuleWizardStep.form

https://github.com/JetBrains/intellij-community/blob/426691f472c4dfb85878ad7cb7ce23144788ca6d/plugins/gradle/src/org/jetbrains/plugins/gradle/service/project/wizard/GradleModuleWizardStep.java

https://github.com/JetBrains/intellij-community/blob/master/plugins/devkit/src/module/PluginModuleBuilder.java

template
https://github.com/JetBrains/intellij-community/blob/f31f390caee44f3b558f98711c57ed94e3ff580c/plugins/gradle/src/META-INF/plugin.xml#L106

More Settings
https://github.com/JetBrains/intellij-community/blob/216ca13bce64c431e0614e369452ec1ab2dc4114/java/idea-ui/src/com/intellij/ide/util/newProjectWizard/SelectTemplateStep.java#L94

**Comment by shiraji** [comment]
close for now
